[package]
name = "esp-backtrace"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-println = { git = "https://github.com/esp-rs/esp-println.git", optional = true, default-features = false }
xtensa-lx-rt = { version = "0.11.0", optional = true }
riscv = { version = "0.8.0", optional = true }
esp32c3-hal = { package = "esp32c3-hal", git = "https://github.com/esp-rs/esp-hal.git", optional = true }

[features]
esp32c3 = [ "esp-println?/esp32c3", "riscv", "esp32c3-hal" ]
esp32 = [ "esp-println?/esp32", "xtensa-lx-rt/esp32" ]
esp32s2 = [ "esp-println?/esp32s2", "xtensa-lx-rt/esp32s2" ]
esp32s3 = [ "esp-println?/esp32s3", "xtensa-lx-rt/esp32s3" ]
panic-handler = [ "esp-println" ]
exception-handler = [ "esp-println" ]
print-uart = [ "esp-println/uart" ]
print-jtag-serial = [ "esp-println/jtag_serial" ]
print-rtt = [ "esp-println/rtt"]
